import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/main.module.scss'
import { Header } from '@/containers/Header'
import { Footer } from '@/containers/Footer'
import { ParticlesContainer } from '@/components/Particles'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ParticlesContainer />
      <section className={styles.content}>
        <main className={styles.main}>
          <article>Article</article>
          <aside>Optional aside</aside>
        </main>
        <Footer />
      </section>
      <section id="portal"></section>
    </>
  )
}
