import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/main.module.scss'
import { Header } from '@/containers/Header'
import { Footer } from '@/containers/Footer'
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

const ParticlesContainer = dynamic(() => import('../components/Particles').then(module => module.ParticlesContainer), {
  ssr: false,
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParticlesContainer />
      <Header />
      <main className={styles.content}>
        <section className={styles.main}>
          <article>Article</article>
          <aside>Optional aside</aside>
        </section>
        <Footer />
      </main>
      <section id="portal"></section>
    </>
  )
}
