import Image from 'next/image'
import { Inter } from '@next/font/google'
import '@/styles/globals.css'
import styles from '@/styles/main.module.scss'
import { Header } from '@/containers/Header'
import { Footer } from '@/containers/Footer'
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

const ParticlesContainer = dynamic(() => import('../components/Particles').then(module => module.ParticlesContainer), {
  ssr: false,
})

export const metadata = {
  title: 'Mauro Colella',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
}

export default function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <ParticlesContainer />
      <Header />
      <main className={styles.content}>
        <section className={styles.main}>
          <article>{children}</article>
          <aside>Optional aside</aside>
        </section>
        <Footer />
      </main>
      <section id="portal"></section>
      </body>
    </html>
  )
}
