export const metadata = {
  title: 'Mauro Colella - Resume',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
}

export default function ResumePage() {
  return <>Hello World</>
}
